// Exemplos 
// PODE SER EXIBIR TEXTO COM ASPAS SIMPLES OU DUBLAS 
// PODE SER EXIBIR TEXTO COM ASPAS SIMPLES OU DUBLAS NO MESMO CONSOLE.LOG USANDO CRASE 

console.log("HELLO WORLD" , 'HELLO WORLD'); // MOSTRA UM TEXTO = STRING
console.log(`"HELLO WORLD" , 'HELLO WORLD'`) // METODO MUITO COMUM CHAMDO TEMPLE STRING
console.log(26); // MOSTRA UM NUMERO NUMERO INTEIRO
console.log(15.6); // MOSTRA UM NUMERO NUMERO REAL = FLOAT